# .streamlit/secrets.toml

[snowflake]
user = "ABHAY2004"
password = "Abhay@7505991639"
account = "IHHCOBH-KM69371"  
warehouse = "DS_ADMIN_WH"
database = "DS_GROUP_DB"
schema = "ADMIN_PORTAL"
role = "ACCOUNTADMIN"





